// apps/producer_storyboard/src/lib/components/novel/ChapterTree.svelte
<script lang="ts">
	import { browser } from '$app/environment';
	import { onMount } from 'svelte';
	import { novelStore } from '$lib/stores/novelStore.svelte';
	import { novelClient } from '$lib/grpc/novelClient';
	import { create } from '@bufbuild/protobuf';
	import {
		ListChaptersRequestSchema,
		CreateChapterRequestSchema,
	} from '$lib/grpc/generated/novel/v1/chapter_pb';
	import type { Chapter } from '$lib/grpc/generated/novel/v1/chapter_pb';

	type Props = {
		novelId: string;
		onChapterSelect?: (chapterId: string | null) => void;
		selectedChapterId?: string | null;
	};

	let { novelId, onChapterSelect, selectedChapterId }: Props = $props();

	let chapters = $state<Chapter[]>([]);
	let loading = $state(true);
	let error = $state<string | null>(null);
	let creating = $state(false);

	onMount(() => {
		if (browser && novelId) {
			loadChapters();
		}
	});

	async function loadChapters() {
		if (!novelId) return;

		try {
			loading = true;
			error = null;

			const request = create(ListChaptersRequestSchema, {
				novelProjectId: novelId,
			});

			const response = await novelClient.listChapters(request);
			chapters = response.chapters || [];
			novelStore.setChapters(chapters);
		} catch (err) {
			console.error('Failed to load chapters:', err);
			error = err instanceof Error ? err.message : 'Failed to load chapters';
		} finally {
			loading = false;
		}
	}

	async function handleCreateChapter() {
		if (!novelId) return;

		try {
			creating = true;
			const nextOrder = chapters.length > 0
				? Math.max(...chapters.map(c => c.orderIndex || 0)) + 1
				: 1;

			const request = create(CreateChapterRequestSchema, {
				novelProjectId: novelId,
				title: `Chapter ${nextOrder}`,
				orderIndex: nextOrder,
			});

			const newChapter = await novelClient.createChapter(request);
			if (newChapter) {
				await loadChapters();
				if (onChapterSelect && newChapter.id) {
					onChapterSelect(newChapter.id);
				}
			}
		} catch (err) {
			console.error('Failed to create chapter:', err);
			error = err instanceof Error ? err.message : 'Failed to create chapter';
		} finally {
			creating = false;
		}
	}

	function handleChapterClick(chapterId: string) {
		if (onChapterSelect) {
			onChapterSelect(chapterId);
		}
	}
</script>

<div class="chapter-tree">
	<div class="chapter-tree-header">
		<h3 class="chapter-tree-title">Chapters</h3>
		<button
			type="button"
			onclick={handleCreateChapter}
			disabled={creating}
			class="create-chapter-btn"
			title="Create new chapter"
		>
			+
		</button>
	</div>

	{#if loading}
		<div class="loading">Loading chapters...</div>
	{:else if error}
		<div class="error">{error}</div>
	{:else if chapters.length > 0}
		<ul class="chapter-list">
			{#each chapters as chapter (chapter.id)}
				<li
					onclick={() => handleChapterClick(chapter.id)}
					class="chapter-item"
					class:selected={selectedChapterId === chapter.id}
				>
					{chapter.orderIndex || 0}. {chapter.title || 'Untitled'}
				</li>
			{/each}
		</ul>
	{:else}
		<div class="empty-state">
			<p>No chapters found</p>
			<button
				type="button"
				onclick={handleCreateChapter}
				disabled={creating}
				class="create-first-chapter-btn"
			>
				Create your first chapter
			</button>
		</div>
	{/if}
</div>

<style>
	.chapter-tree {
		margin-bottom: 1rem;
	}

	.chapter-tree-header {
		display: flex;
		justify-content: space-between;
		align-items: center;
		margin-bottom: 0.5rem;
	}

	.chapter-tree-title {
		margin: 0;
		font-weight: 600;
		font-size: 1rem;
	}

	.create-chapter-btn {
		padding: 0.25rem 0.5rem;
		font-size: 0.75rem;
		background-color: #10b981;
		color: white;
		border: none;
		border-radius: 0.25rem;
		cursor: pointer;
		transition: background-color 0.2s;
	}

	.create-chapter-btn:hover:not(:disabled) {
		background-color: #059669;
	}

	.create-chapter-btn:disabled {
		opacity: 0.5;
		cursor: not-allowed;
	}

	.chapter-list {
		list-style: none;
		padding: 0;
		margin: 0;
	}

	.chapter-item {
		padding: 0.5rem;
		cursor: pointer;
		border-radius: 0.25rem;
		transition: background-color 0.2s;
		margin-bottom: 0.25rem;
	}

	.chapter-item:hover {
		background-color: var(--bg-hover, #f3f4f6);
	}

	.chapter-item.selected {
		background-color: #dbeafe;
		border: 1px solid #93c5fd;
	}

	.empty-state {
		color: var(--text-secondary, #6b7280);
		font-size: 0.875rem;
	}

	.empty-state p {
		margin-bottom: 0.5rem;
	}

	.create-first-chapter-btn {
		color: #3b82f6;
		text-decoration: underline;
		background: none;
		border: none;
		cursor: pointer;
		font-size: 0.75rem;
		padding: 0;
	}

	.create-first-chapter-btn:hover:not(:disabled) {
		color: #2563eb;
	}

	.create-first-chapter-btn:disabled {
		opacity: 0.5;
		cursor: not-allowed;
	}

	.loading,
	.error {
		padding: 0.5rem;
		font-size: 0.875rem;
	}

	.error {
		color: var(--error-color, #ef4444);
	}
</style>

// producerv3/src/components/editor/ChapterTree.tsx
/**
 * @context https://gftd.ai/ontology/epub-editor#
 * @type cpm:Activity
 * @id https://gftd.ai/activity/manage-chapters
 * 
 * Chapter tree component for managing EPUB chapters
 */
'use client';

import { useQuery, useMutation } from '@apollo/client';
import { GET_CHAPTERS } from '@/lib/graphql/queries';
import { CREATE_CHAPTER } from '@/lib/graphql/mutations';

interface ChapterTreeProps {
  epubId: string;
  onChapterSelect?: (chapterId: string) => void;
  selectedChapterId?: string;
}

export function ChapterTree({ epubId, onChapterSelect, selectedChapterId }: ChapterTreeProps) {
  const { data, loading, error, refetch } = useQuery(GET_CHAPTERS, {
    variables: { epubId },
  });

  const [createChapter, { loading: creating }] = useMutation(CREATE_CHAPTER, {
    onCompleted: (data) => {
      if (data?.createChapter?.id) {
        onChapterSelect?.(data.createChapter.id);
        refetch();
      }
    },
  });

  const handleCreateChapter = async () => {
    const chapters = data?.chapters || [];
    const nextOrder = chapters.length > 0 
      ? Math.max(...chapters.map((c: { order: number }) => c.order)) + 1 
      : 1;
    
    await createChapter({
      variables: {
        input: {
          epubId,
          title: `Chapter ${nextOrder}`,
          order: nextOrder,
          contentHtml: '',
        },
      },
    });
  };

  if (loading) return <div className="p-2 text-gray-500">Loading chapters...</div>;
  if (error) return <div className="p-2 text-red-500">Error loading chapters: {error.message}</div>;

  return (
    <div className="chapter-tree mb-4">
      <div className="flex justify-between items-center mb-2">
        <h3 className="font-bold">Chapters</h3>
        <button
          onClick={handleCreateChapter}
          disabled={creating}
          className="px-2 py-1 text-xs bg-green-500 text-white rounded hover:bg-green-600 disabled:opacity-50"
          title="Create new chapter"
        >
          +
        </button>
      </div>
      {data?.chapters && data.chapters.length > 0 ? (
        <ul className="list-none p-0">
          {data.chapters.map((chapter: { id: string; title: string; order: number }) => (
            <li
              key={chapter.id}
              onClick={() => onChapterSelect?.(chapter.id)}
              className={`p-2 cursor-pointer rounded transition-colors ${
                selectedChapterId === chapter.id
                  ? 'bg-blue-100 border border-blue-300'
                  : 'hover:bg-gray-100'
              }`}
            >
              {chapter.order}. {chapter.title || 'Untitled'}
            </li>
          ))}
        </ul>
      ) : (
        <div className="text-gray-500 text-sm">
          <p className="mb-2">No chapters found</p>
          <button
            onClick={handleCreateChapter}
            disabled={creating}
            className="text-blue-500 hover:text-blue-600 underline text-xs disabled:opacity-50"
          >
            Create your first chapter
          </button>
        </div>
      )}
    </div>
  );
}
